name: test

on:
  push: 
    branches: 
      - master
  schedule:
    - cron: '* * * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test
        uses: actions/checkout@v2

      - name: 'Set up python'
        uses: actions/checkout@v1
        with:
          python-version: 3.7
      
      - name: 'Install B'
        run: pip install beautifulsoup4
        
      - name: 'Install R'
        run: pip install requests
        
      - name: 'Working'
        run: python cd../colckin-bot/user.py
        

