name: test

on:
  push: 
    branches: [main]
  schedule:
    - cron: '0 0,13 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up python'
        uses: actions/checkout@v1
        with:
          python-version: 3.7
      - name: 'pip re'
        run: pip install requests
        
      - name: 'pip bs'
        run: pip install beautifulsoup4
        
    #  - name: 'pip lxml'
    #    run: conda install lxml==3.7.0
      
      - name: 'Working'
        run: bash ./colckin-bot/main.sh
        
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 打卡成功！
          to: 1079955876@qq.com
          from: clockin-bot


